apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  destination:
    namespace: my-namespace
    server: "https://kubernetes.default.svc"
  source:
    path: test-app-use-git-action
    repoURL: "https://github.com/whyy9527/test-environmental-with-Kubernetes.git"
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
