apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  destination:
    name: ""
    namespace: ""
    server: "https://kubernetes.default.svc"
  source:
    path: deployment.yaml
    repoURL: "https://github.com/whyy9527/test-environmental-with-Kubernetes.git"
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated: null
