name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: v20.11.1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wuhaoyang123/my-image-name:${{github.run_number}}

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: wuhaoyang123
          password: dckr_pat_pUXy0s_CYaMKzEBuO3XXiyshz-I

      - name: Push Docker image to Docker Hub
        run: docker push wuhaoyang123/my-image-name:${{github.run_number}}
